// <auto-generated />
namespace WebInventoryProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tableInvTransferDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tableInvTransferDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202109181529573_tableInvTransferDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
