// <auto-generated />
namespace WebInventoryProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateUsertABLE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateUsertABLE));
        
        string IMigrationMetadata.Id
        {
            get { return "202207191921284_updateUsertABLE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
